### ISSUE TITLE
 Callback API

### ISSUE THREAD

**Issue by vovanb** [kasthack/kasthack.vksharp#13]
Hello,
can you please provide example of using Callback API?

**Comment by kasthack** [comment]
@vovanb It's not supported yet.

The thing is, vksharp is kinda dead now. The only few commits to the repository for the past year were README updates. Therefore, callback API support is most likely not coming anytime soon:

![image](https://user-images.githubusercontent.com/1292818/34891161-8e137324-f7e5-11e7-9cba-9ee643652d87.png)

[Citrina](/khrabrovart/Citrina) should work for you. I haven't tried their implementation but they use official API schema, so, I assume it's pretty good.

**Comment by vovanb** [comment]
Thanks for reply - left there also question how to use their callback...
